<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/anhui.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/aomen.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/beijing.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chongqing.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fujian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gansu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/guangdong.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/guangxi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/guizhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hainan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hebei.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/heilongjiang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/henan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hubei.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hunan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiangsu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiangxi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jilin.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/liaoning.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/neimenggu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/ningxia.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qinghai.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shandong.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shanghai.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shanxi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shanxi1.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/sichuan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taiwan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tianjin.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xianggang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinjiang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xizang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yunnan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baoding.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tangshan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/cangzhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chengde.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/handan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hengshui.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/langfang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qinhuangdao.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shijiazhuang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xingtai.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhangjiakou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhejiang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/alashanmeng.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/anshan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/bayanzhuoer.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baicheng.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baishan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baotou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/benxi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chaoyang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chifeng.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dalian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/daqing.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dandong.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/eerduosi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fushun.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fuxin.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/haerbin.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hangzhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hegang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/heihe.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huhehaote.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hulunbeier.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huludao.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huzhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jixi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jilin1.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiamusi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiaxing.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jinhua.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jinzhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lishui.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/liaoyang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/liaoyuan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/mudanjiang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/ningbo.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/panjin.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qitaihe.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qiqihaer.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/quzhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shaoxing.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shenyang.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shuangyashan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/siping.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/songyuan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/suihua.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taizhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tieling.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tonghua.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tongliao.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wenzhou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wuhai.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wulanchabu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xilinguole.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xingan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yanbianchaoxianzu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yichun.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yingkou.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/changchun.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhoushan.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/binxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/angangxiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baiquanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fuerlajiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fuyuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gannanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jianhuaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/kedongxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/keshanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longjiangxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longshaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/meilisidawoerzuqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/naheshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nianzishanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tailaixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tiefengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yianxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chengzihequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/didaoqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hengshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hulinshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jidongxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiguanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lishuqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/mashanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/mishanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baoshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/datongqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dongshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/duerbotemengguzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gongnongqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/honggangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jianshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jixianxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lindianxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lingdongqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longfengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/luoobeixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nanshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/ranghuluqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/raohexian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/saertuqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/sifangtaiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/suibinxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xiangyangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinganqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/youyixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhaoyuanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhaozhouxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/aihuiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/beianshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/bolixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dongfengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fujinshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fuyuanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huachuanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huananxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiaoqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nenjiangxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qianjinqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qiezihequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/sunwuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tangyuanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taoshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tongjiangshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wudalianchishi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xiangyangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinxingqu1.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xunkexian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/andashi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/beilinqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hailunshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/humaxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiagedaqiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lanxixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/mingshuixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/mohexian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qinganxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qinggangxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/suilingxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tahexian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wangkuixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhaodongshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/cuiluanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dailingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hongxingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiayinxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jinshantunqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/meixiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nanchaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shangganlingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tangweanghequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tielishi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wumahequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wuyilingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wuyingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xilinqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinqingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yichunqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/youhaoqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/changyiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chaoyangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chuanyingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dehuishi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/erdaoqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fengmanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huadianshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiaoheshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiutaiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/kuanchengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longtanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lvyuanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nanguanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nonganxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/panshishi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shuangyangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shulanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yongjixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yushushi.js" type="text/javascript"></script>

<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/antuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/changbaichaoxianzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/changlingxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/daanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dongchangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dongfengxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dongliaoxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dunhuashi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/erdaojiangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fusongxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fuyushi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gongzhulingshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/helongshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huinanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hunchunshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hunjiangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jiangyuanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jianshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jingyuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/linjiangshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lishuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/liuhexian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longjingshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/meihekoushi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/ningjiangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qiananxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qianguoerluosi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shaungliaoshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taobeiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taonanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tiedongqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tiexiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tonghuaxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tongyuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tumenshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wangqingxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xianqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yanjishi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yitongmanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhenlaixian.js" type="text/javascript"></script>

<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/baitaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/bayuquanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/beipiaoshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/beizhenshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/benximanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/changhaixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/changtuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/chaoyangxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dashiqiaoshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dawaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dengtashi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/donggangshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/dongzhouqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fushunxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/fuxinmengguzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gaizhoushi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/ganjingziqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gongchanglingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/gutaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/haichengshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/haizhouqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/heishanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/hongweiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/huairenmanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jianchangxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jianpingxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/jinzhouqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/kaiyuanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/kalaqinzuoyimengguzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/kuandianmanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/laobianqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lianshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/liaoyangxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tongyuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/linghaishi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/linghequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lingyuanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lishanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longchengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/longgangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/lvshunkouqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/mingshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nanfenqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/nanpiaoqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/panshanxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/pingshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/pulandianqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qianshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qinghemenqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qinghequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/qingyuanmanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shahekouqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shaungtaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shuangtaiziqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/shunchengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/suizhongxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taianxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taihequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taipingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/taizihequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tiaobingshanshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tiedongqu1.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/tiexiqu1.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wafangdianshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wanghuaqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/wenshengqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xifengxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xigangqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xihequ.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xihuqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinbinmanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinfuqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xingchengshi.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinglongtaiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xinqiuqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xishiqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/xiuyanmanzuzizhixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yinzhouqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yixian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/yuanbaoqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhangwuxian.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhanqianqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhenanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhenxingqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhongshanqu.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/rapast/datacenter/screen/common/zhuangheshi.js" type="text/javascript"></script>















